services:
  db:
    image: postgres:16.8
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ai-finance

##TODO: add volume for db
  ai:
    image: ollama/ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
#TODO: automate the mistral model download

  api:
    image: ai-finance:0.1
    ports:
      - "8080:8080"
    depends_on:
      - db
      - ai
volumes:
  ollama_data: