spring.application.name=ai-service
spring.datasource.url=jdbc:postgresql://localhost:5432/ai-finance
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000

api.jwt.public.key=classpath:keys/public_key.pub
api.jwt.private.key=classpath:keys/private_key.priv

#config for docker
#spring.datasource.url=jdbc:postgresql://db:5432/ai-finance
#spring.flyway.enabled=false
#spring.flyway.locations=classpath:db/migration

#spring.ai.ollama.chat.model=mistral
#spring.ai.chat.client.enabled=true
#spring.ai.ollama.base-url=http://ai:11434
#spring.ai.ollama.chat.options.temperature=0.5
