spring.application.name=finance-service

spring.datasource.url=jdbc:postgresql://localhost:5432/ai-finance
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000

api.jwt.public.key=classpath:keys/public_key.pub
api.jwt.private.key=classpath:keys/private_key.priv