CREATE TYPE expense_type AS ENUM ('FOOD', 'TRANSPORT', 'ENTERTAINMENT', 'SHOPPING', 'AESTHETIC', 'HEALTH', 'EDUCATION', 'OTHER');
ALTER TABLE expense
ADD COLUMN type expense_type NOT NULL DEFAULT 'OTHER';